version: "3.8"
name: digitaltwingps

services:
  run-server:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    ports:
      - "${FLASK_PORT:-5050}:${FLASK_PORT:-5050}"
    env_file:
      - ../.env
    volumes:
      - ..:/workspace:cached
